export const ERROR = 'ERROR';
// LAYOUT
export const CHANGE_COLOR_THEME = 'CHANGE_COLOR_THEME';
// DOCUMENTS
export const GET_ALL_DOCUMENTS = 'GET_ALL_DOCUMENTS';
export const GET_ALL_FOLDERS = 'GET_ALL_FOLDERS';
export const GET_ARCHIVES = 'GET_ARCHIVES';
export const UPDATE_ARCHIVES = 'UPDATE_ARCHIVES';
export const CHANGE_PARENT = 'CHANGE_PARENT';
export const SELECT_DOCUMENT = 'SELECT_DOCUMENT';
export const SET_LOADING_DOCUMENTS = 'SET_LOADING_DOCUMENTS';
// AUTH
export const LOAD_USER = 'LOAD_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOGOUT = 'LOGOUT';
// REVISIONS
export const GET_REVISIONS = 'GET_REVISIONS';
export const ADD_REVISION = 'ADD_REVISION';
export const UPDATE_REVISION = 'UPDATE_REVISION';
export const CLEAR_REVISIONS = 'CLEAR_REVISIONS';
export const SET_LOADING_REVISIONS = 'SET_LOADING_REVISIONS';
// SOCKET
export const ADD_FOLDER = 'ADD_FOLDER';
export const UPDATE_FOLDER = 'UPDATE_FOLDER';
export const DELETE_FOLDER = 'DELETE_FOLDER';
export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';
export const ARCHIVE_DOCUMENT = 'ARCHIVE_DOCUMENT';
export const SET_LOADING_AUTH = 'SET_LOADING_AUTH';
